### ISSUE TITLE
Choose test datasets

### ISSUE THREAD

**Issue by neortega25** [NeuroHackademy2024/BIDSInspec#4]
Looked through the datasets within OpenNEURO to select a BIDS compliant dataset for our tests.

**Comment by neortega25** [comment]
Informed A.P. of the following datasets.

OpenNEURO Datasets
I have selected 2 potential datasets we can use. Both of them have valid BIDS validation, however one of them has 3 warnings.
[Accession Number ds004730](https://openneuro.org/datasets/ds004730/versions/1.0.0) [N=10]
[Accession Number ds001705](https://openneuro.org/datasets/ds001705/versions/1.0.1) [N=5]
Both datasets have anat and pet

**Comment by aptinis** [comment]
These 2 datasets look great! We might also want to use 1 subject from the [bids-examples](https://github.com/bids-standard/bids-examples) that has dwi or func since ideally we'd have special figures generated for those modalities in the reports.

**Comment by neortega25** [comment]
Okay, will get that subject for us. Also, yesterday I was troubleshooting getting the above dataset downloaded. I was able to get them to load on the NeuroHackademy Jupyter Notebook; but then I was having issues doing this on my local machine.

**Comment by neortega25** [comment]
This BIDS directory has anat, func, and dwi 

[ds114](https://github.com/bids-standard/bids-examples/tree/master/ds114)

**Comment by aptinis** [comment]
Nice! It seems weird to me though that there aren't any json sidecars alongside the niftis? The dwi folder is also missing the bvec and bvec files. I thought it would be cool to plot the dwi bvec file so we may want to try a different BIDS example.

**Comment by arokem** [comment]
IIRC, individual sidecars are not required for neuroimaging files (though they are nice to have). 

The bvec and bval are the same for all of the DWI acquisitions in this dataset, so they are stored in the top level directory and are "inherited" by all other directories (that's the BIDS "inheritance principle" in action).

**Comment by aptinis** [comment]
> IIRC, individual sidecars are not required for neuroimaging files (though they are nice to have).

Oh interesting, I guess I got use to them being so common with tools like `dcm2niix`. If there is no JSON sidecar for a specific scan type then it may effect the protocol validation.

> The bvec and bval are the same for all of the DWI acquisitions in this dataset, so they are stored in the top level directory and are "inherited" by all other directories (that's the BIDS "inheritance principle" in action).

Oh yes of course. I do see the bvec/bval files in the root of the BIDS directory, thank you! I had tunnel vision from how I use BIDS. That'll work perfectly for 1 particular figure I had in mind.

Also @neortega25 just a heads up all the raw data (niftis) in all the BIDS directories found in [bids-examples](https://github.com/bids-standard/bids-examples) are actually empty! They give examples of the directory structure and auxillary files (ex. bvec, bval, events.tsv etc...) even though the actual nifti files are empty. These BIDS datasets are good for writing lightweight software tests since the niftis are empty. If we want a BIDS directory with actual nifti data for testing (ex. image shape for protocol validation or plotting nifti as mosaic figure for a report) then we'll use the examples from open neuro. Although in this case I don't know if it's common practice to have real test data stored within the repo or if we should just use it to test our package separately. @arokem let us know if you have any advice or thoughts on test data!
