### ISSUE TITLE
Review NiReports and Pybids for prelim report implementation

### ISSUE THREAD

**Issue by neortega25** [NeuroHackademy2024/BIDSInspec#7]
https://github.com/nipreps/nireports/

https://bids-standard.github.io/pybids/

**Comment by aptinis** [comment]
I've started on this issue. It turns out the `pybids` reports only generate a description of the sequences. It's intended to help researchers write methods sections for papers (and is very experimental at the moment). I think what we want will be nireports which consists of reportlets and an assembler that generate the html reports similar to fmriprep.
